# Location of top-level MicroPython directory
MPY_DIR = ../../..

# Name of module (different to built-in framebuf so it can coexist)
MOD = framebuf_utils

# Source files (.c or .py)
SRC = framebuf_utils.c

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin)
ARCH = armv7m

include $(MPY_DIR)/py/dynruntime.mk
